//
/*
Lee histosTest2.root, producido por anaTona2.C y une y hace las graficas
con mejor presentacion 
Author: Héctor Bello Martínez
for: ALICE collaboration
*/
void readHistotest2(){
  
  TFile *f1=TFile::Open("histosTest2.root");
// Graficas de Ratios
  TCanvas* c0 = new TCanvas("c0","THDRatio0",200,10,800,600);
  TH1D *RatioPi0=(TH1D *)f1->Get("Ratio_Pi_RecSt_To_GenSt_0");
  TH1D *RatioK0=(TH1D *)f1->Get("Ratio_K_RecSt_To_GenSt_0");
  TH1D *RatioP0=(TH1D *)f1->Get("Ratio_P_RecSt_To_GenSt_0");
  RatioPi0->SetTitle("Razones de esfericidad");
  RatioPi0->GetXaxis()->SetTitle("P_{t} (GeV)");
  RatioPi0->GetYaxis()->SetTitle("Ratio");
  RatioPi0->GetXaxis()->SetRange(0,50);
  RatioPi0->SetMarkerColor(2);
  RatioK0->SetMarkerColor(3);
  RatioP0->SetMarkerColor(4);
  RatioPi0->SetMarkerStyle(20);
  RatioK0->SetMarkerStyle(20);
  RatioP0->SetMarkerStyle(20);
  RatioPi0->Sumw2();
  RatioK0->Sumw2();
  RatioP0->Sumw2();
  RatioPi0->Draw();
  leg0 = new TLegend(0.1,0.7,0.48,0.9);
  leg0->SetHeader("Razones de ESD/GEN sin cortes para");
  leg0->AddEntry(RatioPi0,"piones","p");
  leg0->AddEntry(RatioK0," kaones","p");
  leg0->AddEntry(RatioP0,"protones","p");
  leg0->Draw();
  RatioK0->Draw("sames");
  RatioP0->Draw("sames");

  TCanvas* c1 = new TCanvas("c1","THDRatio1",200,10,800,600);
  TH1D *RatioPi1=(TH1D *)f1->Get("Ratio_Pi_RecSt_To_GenSt_1");
  TH1D *RatioK1=(TH1D *)f1->Get("Ratio_K_RecSt_To_GenSt_1");
  TH1D *RatioP1=(TH1D *)f1->Get("Ratio_P_RecSt_To_GenSt_1");
  RatioPi1->SetTitle("Razones de esfericidad");
  RatioPi1->GetXaxis()->SetTitle("P_{t} (GeV)");
  RatioPi1->GetYaxis()->SetTitle("Ratio");
  RatioPi1->GetXaxis()->SetRange(0,50);
  RatioPi1->SetMarkerColor(2);
  RatioK1->SetMarkerColor(3);
  RatioP1->SetMarkerColor(4);
  RatioPi1->SetMarkerStyle(20);
  RatioK1->SetMarkerStyle(20);
  RatioP1->SetMarkerStyle(20);
  RatioPi1->Sumw2();
  RatioK1->Sumw2();
  RatioP1->Sumw2();
  RatioPi1->Draw();
  leg1 = new TLegend(0.1,0.7,0.48,0.9);
  leg1->SetHeader("Razones de ESD/GEN con cortes 0<S_{t}<0.2, para");
  leg1->AddEntry(RatioPi1,"piones","p");
  leg1->AddEntry(RatioK1," kaones","p");
  leg1->AddEntry(RatioP1,"protones","p");
  leg1->Draw();
  RatioK1->Draw("sames");
  RatioP1->Draw("sames"); 
  
  TCanvas* c2 = new TCanvas("c2","THDRatio2",200,10,800,600);
  TH1D *RatioPi2=(TH1D *)f1->Get("Ratio_Pi_RecSt_To_GenSt_2");
  TH1D *RatioK2=(TH1D *)f1->Get("Ratio_K_RecSt_To_GenSt_2");
  TH1D *RatioP2=(TH1D *)f1->Get("Ratio_P_RecSt_To_GenSt_2");
  RatioPi2->SetTitle("Razones de esfericidad");
  RatioPi2->GetXaxis()->SetTitle("P_{t} (GeV)");
  RatioPi2->GetYaxis()->SetTitle("Ratio");
  RatioPi2->GetXaxis()->SetRange(0,50);
  RatioPi2->SetMarkerColor(2);
  RatioK2->SetMarkerColor(3);
  RatioP2->SetMarkerColor(4);
  RatioPi2->SetMarkerStyle(20);
  RatioK2->SetMarkerStyle(20);
  RatioP2->SetMarkerStyle(20);
  RatioPi2->Sumw2();
  RatioK2->Sumw2();
  RatioP2->Sumw2();
  RatioPi2->Draw();
  leg2 = new TLegend(0.1,0.7,0.48,0.9);
  leg2->SetHeader("Razones de ESD/GEN con cortes 0.2<S_{t}<0.4, para");
  leg2->AddEntry(RatioPi2,"piones","p");
  leg2->AddEntry(RatioK2," kaones","p");
  leg2->AddEntry(RatioP2,"protones","p");
  leg2->Draw();
  RatioK2->Draw("sames");
  RatioP2->Draw("sames");
  
  TCanvas* c3 = new TCanvas("c3","THDRatio3",200,10,800,600);
  TH1D *RatioPi3=(TH1D *)f1->Get("Ratio_Pi_RecSt_To_GenSt_3");
  TH1D *RatioK3=(TH1D *)f1->Get("Ratio_K_RecSt_To_GenSt_3");
  TH1D *RatioP3=(TH1D *)f1->Get("Ratio_P_RecSt_To_GenSt_3");
  RatioPi3->SetTitle("Razones de esfericidad");
  RatioPi3->GetXaxis()->SetTitle("P_{t} (GeV)");
  RatioPi3->GetYaxis()->SetTitle("Ratio");
  RatioPi3->GetXaxis()->SetRange(0,50);
  RatioPi3->SetMarkerColor(2);
  RatioK3->SetMarkerColor(3);
  RatioP3->SetMarkerColor(4);
  RatioPi3->SetMarkerStyle(20);
  RatioK3->SetMarkerStyle(20);
  RatioP3->SetMarkerStyle(20);
  RatioPi3->Sumw2();
  RatioK3->Sumw2();
  RatioP3->Sumw2();
  RatioPi3->Draw();
  leg3 = new TLegend(0.1,0.7,0.48,0.9);
  leg3->SetHeader("Razones de ESD/GEN con cortes 0.4<S_{t}<0.6, para");
  leg3->AddEntry(RatioPi3,"piones","p");
  leg3->AddEntry(RatioK3," kaones","p");
  leg3->AddEntry(RatioP3,"protones","p");
  leg3->Draw();
  RatioK3->Draw("sames");
  RatioP3->Draw("sames");
 
  TCanvas* c4 = new TCanvas("c4","THDRatio4",200,10,800,600);
  TH1D *RatioPi4=(TH1D *)f1->Get("Ratio_Pi_RecSt_To_GenSt_4");
  TH1D *RatioK4=(TH1D *)f1->Get("Ratio_K_RecSt_To_GenSt_4");
  TH1D *RatioP4=(TH1D *)f1->Get("Ratio_P_RecSt_To_GenSt_4");
  RatioPi4->SetTitle("Razones de esfericidad");
  RatioPi4->GetXaxis()->SetTitle("P_{t} (GeV)");
  RatioPi4->GetYaxis()->SetTitle("Ratio");
  RatioPi4->GetXaxis()->SetRange(0,50);
  RatioPi4->SetMarkerColor(2);
  RatioK4->SetMarkerColor(3);
  RatioP4->SetMarkerColor(4);
  RatioPi4->SetMarkerStyle(20);
  RatioK4->SetMarkerStyle(20);
  RatioP4->SetMarkerStyle(20);
  RatioPi4->Sumw2();
  RatioK4->Sumw2();
  RatioP4->Sumw2();
  RatioPi4->Draw();
  leg4 = new TLegend(0.1,0.7,0.48,0.9);
  leg4->SetHeader("Razones de ESD/GEN con cortes 0.6<S_{t}<0.8, para");
  leg4->AddEntry(RatioPi4,"piones","p");
  leg4->AddEntry(RatioK4," kaones","p");
  leg4->AddEntry(RatioP4,"protones","p");
  leg4->Draw();
  RatioK4->Draw("sames");
  RatioP4->Draw("sames");

  TCanvas* c5 = new TCanvas("c5","THDRatio5",200,10,800,600);
  TH1D *RatioPi5=(TH1D *)f1->Get("Ratio_Pi_RecSt_To_GenSt_5");
  TH1D *RatioK5=(TH1D *)f1->Get("Ratio_K_RecSt_To_GenSt_5");
  TH1D *RatioP5=(TH1D *)f1->Get("Ratio_P_RecSt_To_GenSt_5");
  RatioPi5->SetTitle("Razones de esfericidad");
  RatioPi5->GetXaxis()->SetTitle("P_{t} (GeV)");
  RatioPi5->GetYaxis()->SetTitle("Ratio");
  RatioPi5->GetXaxis()->SetRange(0,50);
  RatioPi5->SetMarkerColor(2);
  RatioK5->SetMarkerColor(3);
  RatioP5->SetMarkerColor(4);
  RatioPi5->SetMarkerStyle(20);
  RatioK5->SetMarkerStyle(20);
  RatioP5->SetMarkerStyle(20);
  RatioPi5->Sumw2();
  RatioK5->Sumw2();
  RatioP5->Sumw2();
  RatioPi5->Draw();
  leg5 = new TLegend(0.1,0.7,0.48,0.9);
  leg5->SetHeader("Razones de ESD/GEN con cortes 0.8<S_{t}<1, para");
  leg5->AddEntry(RatioPi5,"piones","p");
  leg5->AddEntry(RatioK5," kaones","p");
  leg5->AddEntry(RatioP5,"protones","p");
  leg5->Draw();
  RatioK5->Draw("sames");
  RatioP5->Draw("sames");

  // Graficas para S_{t} Generada y ESD

//piones
  TCanvas* c0pi = new TCanvas("c0pi","THDPiptmult0",200,10,800,600);
  TH1D *PiGen0=(TH1D *)f1->Get("hpion_genSt_0");
  TH1D *PiESD0=(TH1D *)f1->Get("hpion_esdSt_0");
  PiGen0->SetTitle("P_{t} vs multiplicidad");
  PiGen0->GetXaxis()->SetTitle("P_{t} (GeV)");
  PiGen0->GetYaxis()->SetTitle("mult");
  PiGen0->GetXaxis()->SetRange(0,50);
  PiGen0->SetMarkerColor(2);
  PiESD0->SetMarkerColor(4);
  PiGen0->SetMarkerStyle(20);
  PiESD0->SetMarkerStyle(20);
  PiGen0->Sumw2();
  PiESD0->Sumw2();
  PiGen0->Draw();
  legpi0 = new TLegend(0.1,0.7,0.48,0.9);
  legpi0->SetHeader("sin cortes para");
  legpi0->AddEntry(PiGen0,"piones gen","p");
  legpi0->AddEntry(PiESD0,"piones ESD","p");
  legpi0->Draw();
  PiESD0->Draw("sames");

  TCanvas* c1pi = new TCanvas("c1pi","THDPiptmult1",200,10,800,600);
  TH1D *PiGen1=(TH1D *)f1->Get("hpion_genSt_1");
  TH1D *PiESD1=(TH1D *)f1->Get("hpion_esdSt_1");
  PiGen1->SetTitle("P_{t} vs multiplicidad");
  PiGen1->GetXaxis()->SetTitle("P_{t} (GeV)");
  PiGen1->GetYaxis()->SetTitle("mult");
  PiGen1->GetXaxis()->SetRange(0,50);
  PiGen1->SetMarkerColor(2);
  PiESD1->SetMarkerColor(3);
  PiGen1->SetMarkerStyle(20);
  PiESD1->SetMarkerStyle(20);
  PiGen1->Sumw2();
  PiESD1->Sumw2();
  PiGen1->Draw();
  legpi1 = new TLegend(0.1,0.7,0.48,0.9);
  legpi1->SetHeader("con cortes  0<S_{t}<0.2, para");
  legpi1->AddEntry(PiGen1,"piones gen","p");
  legpi1->AddEntry(PiESD1,"piones ESD","p");
  legpi1->Draw();
  PiESD1->Draw("sames");

  TCanvas* c2pi = new TCanvas("c2pi","THDPiptmult2",200,10,800,600);
  TH1D *PiGen2=(TH1D *)f1->Get("hpion_genSt_2");
  TH1D *PiESD2=(TH1D *)f1->Get("hpion_esdSt_2");
  PiGen2->SetTitle("P_{t} vs multiplicidad");
  PiGen2->GetXaxis()->SetTitle("P_{t} (GeV)");
  PiGen2->GetYaxis()->SetTitle("mult");
  PiGen2->GetXaxis()->SetRange(0,50);
  PiGen2->SetMarkerColor(2);
  PiESD2->SetMarkerColor(3);
  PiGen2->SetMarkerStyle(20);
  PiESD2->SetMarkerStyle(20);
  PiGen2->Sumw2();
  PiESD2->Sumw2();
  PiGen2->Draw();
  legpi2 = new TLegend(0.1,0.7,0.48,0.9);
  legpi2->SetHeader("con cortes  0.2<S_{t}<0.4, para");
  legpi2->AddEntry(PiGen2,"piones gen","p");
  legpi2->AddEntry(PiESD2,"piones ESD","p");
  legpi2->Draw();
  PiESD2->Draw("sames");
 
  TCanvas* c3pi = new TCanvas("c3pi","THDPiptmult3",200,10,800,600);
  TH1D *PiGen3=(TH1D *)f1->Get("hpion_genSt_3");
  TH1D *PiESD3=(TH1D *)f1->Get("hpion_esdSt_3");
  PiGen3->SetTitle("P_{t} vs multiplicidad");
  PiGen3->GetXaxis()->SetTitle("P_{t} (GeV)");
  PiGen3->GetYaxis()->SetTitle("mult");
  PiGen3->GetXaxis()->SetRange(0,50);
  PiGen3->SetMarkerColor(2);
  PiESD3->SetMarkerColor(3);
  PiGen3->SetMarkerStyle(20);
  PiESD3->SetMarkerStyle(20);
  PiGen3->Sumw2();
  PiESD3->Sumw2();
  PiGen3->Draw();
  legpi3 = new TLegend(0.1,0.7,0.48,0.9);
  legpi3->SetHeader("con cortes  0.4<S_{t}<0.6, para");
  legpi3->AddEntry(PiGen3,"piones gen","p");
  legpi3->AddEntry(PiESD3,"piones ESD","p");
  legpi3->Draw();
  PiESD3->Draw("sames");

  TCanvas* c4pi = new TCanvas("c4pi","THDPiptmult4",200,10,800,600);
  TH1D *PiGen4=(TH1D *)f1->Get("hpion_genSt_4");
  TH1D *PiESD4=(TH1D *)f1->Get("hpion_esdSt_4");
  PiGen4->SetTitle("P_{t} vs multiplicidad");
  PiGen4->GetXaxis()->SetTitle("P_{t} (GeV)");
  PiGen4->GetYaxis()->SetTitle("mult");
  PiGen4->GetXaxis()->SetRange(0,50);
  PiGen4->SetMarkerColor(2);
  PiESD4->SetMarkerColor(3);
  PiGen4->SetMarkerStyle(20);
  PiESD4->SetMarkerStyle(20);
  PiGen4->Sumw2();
  PiESD4->Sumw2();
  PiGen4->Draw();
  legpi4 = new TLegend(0.1,0.7,0.48,0.9);
  legpi4->SetHeader("con cortes  0.6<S_{t}<0.8, para");
  legpi4->AddEntry(PiGen4,"piones gen","p");
  legpi4->AddEntry(PiESD4,"piones ESD","p");
  legpi4->Draw();
  PiESD4->Draw("sames");
  
  TCanvas* c5pi = new TCanvas("c5pi","THDPiptmult5",200,10,800,600);
  TH1D *PiGen5=(TH1D *)f1->Get("hpion_genSt_5");
  TH1D *PiESD5=(TH1D *)f1->Get("hpion_esdSt_5");
  PiGen5->SetTitle("P_{t} vs multiplicidad");
  PiGen5->GetXaxis()->SetTitle("P_{t} (GeV)");
  PiGen5->GetYaxis()->SetTitle("mult");
  PiGen5->GetXaxis()->SetRange(0,50);
  PiGen5->SetMarkerColor(2);
  PiESD5->SetMarkerColor(3);
  PiGen5->SetMarkerStyle(20);
  PiESD5->SetMarkerStyle(20);
  PiGen5->Sumw2();
  PiESD5->Sumw2();
  PiGen5->Draw();
  legpi5 = new TLegend(0.1,0.7,0.48,0.9);
  legpi5->SetHeader("con cortes  0.8<S_{t}<1, para");
  legpi5->AddEntry(PiGen5,"piones gen","p");
  legpi5->AddEntry(PiESD5,"piones ESD","p");
  legpi5->Draw();
  PiESD5->Draw("sames");
// kaones

  TCanvas* c0K = new TCanvas("c0K","THDKptmult0",200,10,800,600);
  TH1D *KGen0=(TH1D *)f1->Get("hkaon_genSt_0");
  TH1D *KESD0=(TH1D *)f1->Get("hkaon_esdSt_0");
  KGen0->SetTitle("P_{t} vs multiplicidad");
  KGen0->GetXaxis()->SetTitle("P_{t} (GeV)");
  KGen0->GetYaxis()->SetTitle("mult");
  KGen0->GetXaxis()->SetRange(0,50);
  KGen0->SetMarkerColor(2);
  KESD0->SetMarkerColor(4);
  KGen0->SetMarkerStyle(20);
  KESD0->SetMarkerStyle(20);
  KGen0->Sumw2();
  KESD0->Sumw2();
  KGen0->Draw();
  legk0 = new TLegend(0.1,0.7,0.48,0.9);
  legk0->SetHeader("sin cortes para");
  legk0->AddEntry(KGen0,"kaones gen","p");
  legk0->AddEntry(KESD0,"kaones ESD","p");
  legk0->Draw();
  KESD0->Draw("sames");

  TCanvas* c1K = new TCanvas("c1K","THDKptmult1",200,10,800,600);
  TH1D *KGen1=(TH1D *)f1->Get("hkaon_genSt_1");
  TH1D *KESD1=(TH1D *)f1->Get("hkaon_esdSt_1");
  KGen1->SetTitle("P_{t} vs multiplicidad");
  KGen1->GetXaxis()->SetTitle("P_{t} (GeV)");
  KGen1->GetYaxis()->SetTitle("mult");
  KGen1->GetXaxis()->SetRange(0,50);
  KGen1->SetMarkerColor(2);
  KESD1->SetMarkerColor(3);
  KGen1->SetMarkerStyle(20);
  KESD1->SetMarkerStyle(20);
  KGen1->Sumw2();
  KESD1->Sumw2();
  KGen1->Draw();
  legk1 = new TLegend(0.1,0.7,0.48,0.9);
  legk1->SetHeader("con cortes  0<S_{t}<0.2, para");
  legk1->AddEntry(KGen1,"kaones gen","p");
  legk1->AddEntry(KESD1,"kaones ESD","p");
  legk1->Draw();
  KESD1->Draw("sames");

  TCanvas* c2K = new TCanvas("c2K","THDKptmult2",200,10,800,600);
  TH1D *KGen2=(TH1D *)f1->Get("hkaon_genSt_2");
  TH1D *KESD2=(TH1D *)f1->Get("hkaon_esdSt_2");
  KGen2->SetTitle("P_{t} vs multiplicidad");
  KGen2->GetXaxis()->SetTitle("P_{t} (GeV)");
  KGen2->GetYaxis()->SetTitle("mult");
  KGen2->GetXaxis()->SetRange(0,50);
  KGen2->SetMarkerColor(2);
  KESD2->SetMarkerColor(3);
  KGen2->SetMarkerStyle(20);
  KESD2->SetMarkerStyle(20);
  KGen2->Sumw2();
  KESD2->Sumw2();
  KGen2->Draw();
  legk2 = new TLegend(0.1,0.7,0.48,0.9);
  legk2->SetHeader("con cortes  0.2<S_{t}<0.4, para");
  legk2->AddEntry(KGen2,"kaones gen","p");
  legk2->AddEntry(KESD2,"kaones ESD","p");
  legk2->Draw();
  KESD2->Draw("sames");
 
  TCanvas* c3K = new TCanvas("c3K","THDKptmult3",200,10,800,600);
  TH1D *KGen3=(TH1D *)f1->Get("hkaon_genSt_3");
  TH1D *KESD3=(TH1D *)f1->Get("hkaon_esdSt_3");
  KGen3->SetTitle("P_{t} vs multiplicidad");
  KGen3->GetXaxis()->SetTitle("P_{t} (GeV)");
  KGen3->GetYaxis()->SetTitle("mult");
  KGen3->GetXaxis()->SetRange(0,50);
  KGen3->SetMarkerColor(2);
  KESD3->SetMarkerColor(3);
  KGen3->SetMarkerStyle(20);
  KESD3->SetMarkerStyle(20);
  KGen3->Sumw2();
  KESD3->Sumw2();
  KGen3->Draw();
  legk3 = new TLegend(0.1,0.7,0.48,0.9);
  legk3->SetHeader("con cortes  0.4<S_{t}<0.6, para");
  legk3->AddEntry(KGen3,"kaones gen","p");
  legk3->AddEntry(KESD3,"kaones ESD","p");
  legk3->Draw();
  KESD3->Draw("sames");

  TCanvas* c4K = new TCanvas("c4K","THDPiptmult4",200,10,800,600);
  TH1D *KGen4=(TH1D *)f1->Get("hkaon_genSt_4");
  TH1D *KESD4=(TH1D *)f1->Get("hkaon_esdSt_4");
  KGen4->SetTitle("P_{t} vs multiplicidad");
  KGen4->GetXaxis()->SetTitle("P_{t} (GeV)");
  KGen4->GetYaxis()->SetTitle("mult");
  KGen4->GetXaxis()->SetRange(0,50);
  KGen4->SetMarkerColor(2);
  KESD4->SetMarkerColor(3);
  KGen4->SetMarkerStyle(20);
  KESD4->SetMarkerStyle(20);
  KGen4->Sumw2();
  KESD4->Sumw2();
  KGen4->Draw();
  legk4 = new TLegend(0.1,0.7,0.48,0.9);
  legk4->SetHeader("con cortes  0.6<S_{t}<0.8, para");
  legk4->AddEntry(KGen4,"kaones gen","p");
  legk4->AddEntry(KESD4,"kaones ESD","p");
  legk4->Draw();
  KESD4->Draw("sames");
  
  TCanvas* c5K = new TCanvas("c5K","THDKptmult5",200,10,800,600);
  TH1D *KGen5=(TH1D *)f1->Get("hkaon_genSt_5");
  TH1D *KESD5=(TH1D *)f1->Get("hkaon_esdSt_5");
  KGen5->SetTitle("P_{t} vs multiplicidad");
  KGen5->GetXaxis()->SetTitle("P_{t} (GeV)");
  KGen5->GetYaxis()->SetTitle("mult");
  KGen5->GetXaxis()->SetRange(0,50);
  KGen5->SetMarkerColor(2);
  KESD5->SetMarkerColor(3);
  KGen5->SetMarkerStyle(20);
  KESD5->SetMarkerStyle(20);
  KGen5->Sumw2();
  KESD5->Sumw2();
  KGen5->Draw();
  legk5 = new TLegend(0.1,0.7,0.48,0.9);
  legk5->SetHeader("con cortes  0.8<S_{t}<1, para");
  legk5->AddEntry(KGen5,"kaones gen","p");
  legk5->AddEntry(KESD5,"kaones ESD","p");
  legk5->Draw();
  KESD5->Draw("sames");

//protones
  TCanvas* c0p = new TCanvas("c0p","THDPptmult0",200,10,800,600);
  TH1D *PGen0=(TH1D *)f1->Get("hproton_genSt_0");
  TH1D *PESD0=(TH1D *)f1->Get("hproton_esdSt_0");
  PGen0->SetTitle("P_{t} vs multiplicidad");
  PGen0->GetXaxis()->SetTitle("P_{t} (GeV)");
  PGen0->GetYaxis()->SetTitle("mult");
  PGen0->GetXaxis()->SetRange(0,50);
  PGen0->SetMarkerColor(2);
  PESD0->SetMarkerColor(4);
  PGen0->SetMarkerStyle(20);
  PESD0->SetMarkerStyle(20);
  PGen0->Sumw2();
  PESD0->Sumw2();
  PGen0->Draw();
  legp0 = new TLegend(0.1,0.7,0.48,0.9);
  legp0->SetHeader("sin cortes para");
  legp0->AddEntry(PGen0,"protones gen","p");
  legp0->AddEntry(PESD0,"protones ESD","p");
  legp0->Draw();
  PESD0->Draw("sames");

  TCanvas* c1p = new TCanvas("c1p","THDPptmult1",200,10,800,600);
  TH1D *PGen1=(TH1D *)f1->Get("hproton_genSt_1");
  TH1D *PESD1=(TH1D *)f1->Get("hproton_esdSt_1");
  PGen1->SetTitle("P_{t} vs multiplicidad");
  PGen1->GetXaxis()->SetTitle("P_{t} (GeV)");
  PGen1->GetYaxis()->SetTitle("mult");
  PGen1->GetXaxis()->SetRange(0,50);
  PGen1->SetMarkerColor(2);
  PESD1->SetMarkerColor(3);
  PGen1->SetMarkerStyle(20);
  PESD1->SetMarkerStyle(20);
  PGen1->Sumw2();
  PESD1->Sumw2();
  PGen1->Draw();
  legp1 = new TLegend(0.1,0.7,0.48,0.9);
  legp1->SetHeader("con cortes  0<S_{t}<0.2, para");
  legp1->AddEntry(PGen1,"protones gen","p");
  legp1->AddEntry(PESD1,"protones ESD","p");
  legp1->Draw();
  PESD1->Draw("sames");

  TCanvas* c2p = new TCanvas("c2p","THDPiptmult2",200,10,800,600);
  TH1D *PGen2=(TH1D *)f1->Get("hproton_genSt_2");
  TH1D *PESD2=(TH1D *)f1->Get("hproton_esdSt_2");
  PGen2->SetTitle("P_{t} vs multiplicidad");
  PGen2->GetXaxis()->SetTitle("P_{t} (GeV)");
  PGen2->GetYaxis()->SetTitle("mult");
  PGen2->GetXaxis()->SetRange(0,50);
  PGen2->SetMarkerColor(2);
  PESD2->SetMarkerColor(3);
  PGen2->SetMarkerStyle(20);
  PESD2->SetMarkerStyle(20);
  PGen2->Sumw2();
  PESD2->Sumw2();
  PGen2->Draw();
  legp2 = new TLegend(0.1,0.7,0.48,0.9);
  legp2->SetHeader("con cortes  0.2<S_{t}<0.4, para");
  legp2->AddEntry(PGen2,"protones gen","p");
  legp2->AddEntry(PESD2,"protones ESD","p");
  legp2->Draw();
  PESD2->Draw("sames");
 
  TCanvas* c3p = new TCanvas("c3p","THDPptmult3",200,10,800,600);
  TH1D *PGen3=(TH1D *)f1->Get("hproton_genSt_3");
  TH1D *PESD3=(TH1D *)f1->Get("hproton_esdSt_3");
  PGen3->SetTitle("P_{t} vs multiplicidad");
  PGen3->GetXaxis()->SetTitle("P_{t} (GeV)");
  PGen3->GetYaxis()->SetTitle("mult");
  PGen3->GetXaxis()->SetRange(0,50);
  PGen3->SetMarkerColor(2);
  PESD3->SetMarkerColor(3);
  PGen3->SetMarkerStyle(20);
  PESD3->SetMarkerStyle(20);
  PGen3->Sumw2();
  PESD3->Sumw2();
  PGen3->Draw();
  legp3 = new TLegend(0.1,0.7,0.48,0.9);
  legp3->SetHeader("con cortes  0.4<S_{t}<0.6, para");
  legp3->AddEntry(PGen3,"protones gen","p");
  legp3->AddEntry(PESD3,"protones ESD","p");
  legp3->Draw();
  PESD3->Draw("sames");

  TCanvas* c4p = new TCanvas("c4p","THDPptmult4",200,10,800,600);
  TH1D *PGen4=(TH1D *)f1->Get("hproton_genSt_4");
  TH1D *PESD4=(TH1D *)f1->Get("hproton_esdSt_4");
  PGen4->SetTitle("P_{t} vs multiplicidad");
  PGen4->GetXaxis()->SetTitle("P_{t} (GeV)");
  PGen4->GetYaxis()->SetTitle("mult");
  PGen4->GetXaxis()->SetRange(0,50);
  PGen4->SetMarkerColor(2);
  PESD4->SetMarkerColor(3);
  PGen4->SetMarkerStyle(20);
  PESD4->SetMarkerStyle(20);
  PGen4->Sumw2();
  PESD4->Sumw2();
  PGen4->Draw();
  legp4 = new TLegend(0.1,0.7,0.48,0.9);
  legp4->SetHeader("con cortes  0.6<S_{t}<0.8, para");
  legp4->AddEntry(PGen4,"protones gen","p");
  legp4->AddEntry(PESD4,"protones ESD","p");
  legp4->Draw();
  PESD4->Draw("sames");
  
  TCanvas* c5p = new TCanvas("c5p","THDPptmult5",200,10,800,600);
  TH1D *PGen5=(TH1D *)f1->Get("hproton_genSt_5");
  TH1D *PESD5=(TH1D *)f1->Get("hproton_esdSt_5");
  PGen5->SetTitle("P_{t} vs multiplicidad");
  PGen5->GetXaxis()->SetTitle("P_{t} (GeV)");
  PGen5->GetYaxis()->SetTitle("mult");
  PGen5->GetXaxis()->SetRange(0,50);
  PGen5->SetMarkerColor(2);
  PESD5->SetMarkerColor(3);
  PGen5->SetMarkerStyle(20);
  PESD5->SetMarkerStyle(20);
  PGen5->Sumw2();
  PESD5->Sumw2();
  PGen5->Draw();
  legp5 = new TLegend(0.1,0.7,0.48,0.9);
  legp5->SetHeader("con cortes  0.8<S_{t}<1, para");
  legp5->AddEntry(PiGen5,"protones gen","p");
  legp5->AddEntry(PiESD5,"protones ESD","p");
  legp5->Draw();
  PESD5->Draw("sames");


}
